#! /bin/sh

# v2025.313
listen_port=12345
server_port=8080

set -e
cleanup() {
	rc=$?
	if test "$fwd_pid"
	then
		wait $fwd_pid || :
	fi
	test $rc = 0 || echo "\"$0\" failed!" >& 2
}
fwd_pid=
trap cleanup 0
trap 'exit $?' INT QUIT TERM HUP

while getopts P:p: opt
do
	case $opt in
		p) listen_port=$OPTART;;
		P) server_port=$OPTARG;;
		*) false || exit
	esac
done
shift `expr $OPTIND - 1 || :`

host=`hostname`
test "$host"

test $# = 1
test -f "$1"

# Will be killed by ^C together with the script.
socat TCP4-LISTEN:"$listen_port",bind="$host",reuseaddr,fork \
	TCP4:127.0.0.1:"$server_port" &

llama-server --port "$server_port" -m "$1"
