#! /bin/sh

# v2025.190
listen_port=12345

set -e
cleanup() {
	rc=$?
	if test "$fwd_pid"
	then
		wait $fwd_pid || :
	fi
	test $rc = 0 || echo "\"$0\" failed!" >& 2
}
fwd_pid=
trap cleanup 0
trap 'exit $?' INT QUIT TERM HUP

while getopts '' opt
do
	case $opt in
		*) false || exit
	esac
done
shift `expr $OPTIND - 1 || :`

host=`hostname`
test "$host"

# Will be killed by ^C together with the script.
socat TCP4-LISTEN:$listen_port,bind="$host",reuseaddr,fork \
	TCP4:127.0.0.1:8080 & fwd_pid=$!

test $# = 1
test -f "$1"

llama-server -m "$1"
